//! Directed Container Law Tests for the SNES Bus
//!
//! A directed container (S, P, o, down, +) satisfies five laws.
//! We test whether the SNES memory bus, viewed as a container where
//! shapes = address space configurations and positions = (bank, addr),
//! respects these laws.
//!
//! The key insight: `down` is address decode. Given a position (bank, addr),
//! `down` maps it to a sub-address-space (the target hardware's local view).
//! The `(+)` operation is address composition through the decode chain.
//!
//! Reference: Ahman, Chapman, Uustalu (2014) "When is a container a comonad?"
//!
//! Generated by /snes-category-sweep

use rsnes::bus::Bus;
use rsnes::rom::{Cartridge, MapMode};

fn test_bus() -> Bus {
    let mut rom = vec![0u8; 0x10000]; // 64KB ROM
    // Plant known values for identity checks
    rom[0] = 0x11;         // bank $00, addr $8000 → ROM offset 0
    rom[0x8000] = 0x22;    // bank $01, addr $8000 → ROM offset 0x8000
    rom[0x100] = 0x33;     // bank $00, addr $8100 → ROM offset 0x100
    // Reset vector
    rom[0x7FFC] = 0x00;
    rom[0x7FFD] = 0x80;
    let cart = Cartridge {
        rom,
        sram: vec![0u8; 0x8000], // 32KB SRAM
        title: "DCONT-TEST".to_string(),
        map_mode: MapMode::LoROM,
        rom_size: 0x10000,
        ram_size: 0x8000,
        country: 0,
        version: 0,
        checksum: 0,
        checksum_complement: 0,
    };
    Bus::new(cart)
}

// ═══════════════════════════════════════════════════════════════════
// HELPERS: Concrete definitions of the directed container operations
// ═══════════════════════════════════════════════════════════════════

/// Address region classification — the "sub-shape" that `down` produces.
/// Each variant represents a distinct hardware target with its own local
/// address space.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Region {
    Wram,       // wram[offset], offset in 0..0x20000
    PpuReg,     // PPU register, local addr in 0x2100..0x213F
    ApuPort,    // APU port, local index 0..3
    WmData,     // WRAM data port (sequential, side-effecting)
    Joypad,     // Joypad serial
    CpuReg,     // CPU internal register, addr in 0x4200..0x42FF
    DmaReg,     // DMA channel register, addr in 0x4300..0x437F
    Rom,        // ROM, local offset computed by LoROM formula
    Sram,       // SRAM, local offset
    OpenBus,    // Unmapped — returns last bus value
}

/// `down`: (bank, addr) → (Region, local_offset)
/// This is the address decode — forward on shapes in container morphism terms.
fn down(bank: u8, addr: u16) -> (Region, u32) {
    let eb = bank & 0x7F;
    match (eb, addr) {
        (0x7E, _) => (Region::Wram, addr as u32),
        (0x7F, _) => (Region::Wram, 0x10000 + addr as u32),

        (0x00..=0x3F, 0x0000..=0x1FFF) => (Region::Wram, addr as u32),
        (0x00..=0x3F, 0x2100..=0x213F) => (Region::PpuReg, addr as u32),
        (0x00..=0x3F, 0x2140..=0x217F) => (Region::ApuPort, (addr & 3) as u32),
        (0x00..=0x3F, 0x2180) => (Region::WmData, 0), // offset is stateful, not positional
        (0x00..=0x3F, 0x4016) => (Region::Joypad, 0),
        (0x00..=0x3F, 0x4200..=0x42FF) => (Region::CpuReg, addr as u32),
        (0x00..=0x3F, 0x4300..=0x437F) => (Region::DmaReg, addr as u32),
        (0x00..=0x3F, 0x8000..=0xFFFF) => {
            let offset = (eb as u32) * 0x8000 + (addr as u32 - 0x8000);
            (Region::Rom, offset)
        }

        (0x40..=0x6F, 0x8000..=0xFFFF) => {
            let offset = (eb as u32) * 0x8000 + (addr as u32 - 0x8000);
            (Region::Rom, offset)
        }

        (0x70..=0x7D, 0x0000..=0x7FFF) => {
            let offset = ((eb - 0x70) as u32) * 0x8000 + addr as u32;
            (Region::Sram, offset)
        }
        (0x70..=0x7D, 0x8000..=0xFFFF) => {
            let offset = (eb as u32) * 0x8000 + (addr as u32 - 0x8000);
            (Region::Rom, offset)
        }

        _ => (Region::OpenBus, 0),
    }
}

// ═══════════════════════════════════════════════════════════════════
// LAW 3: down(down(s, p), q) = down(s, p + q)
// "Subshapes nest correctly"
//
// In emulator terms: if you decode an address to its target, and then
// decode further within that target, the result should equal decoding
// the composed address directly.
//
// For the Bus, this manifests as: aliases (multiple (bank, addr) pairs
// reaching the same hardware target at the same local offset) must all
// agree on the target. Nesting through any alias path gives the same
// result.
// ═══════════════════════════════════════════════════════════════════

// ── Law 3a: Bank mirroring is idempotent ──────────────────────────
// $80-$FF mirrors $00-$7F. Decoding through the mirror must reach
// the same target as decoding the canonical address.
// This is: down(s, mirror(p)) = down(s, p)

#[test]
fn law3_bank_mirror_wram_is_idempotent() {
    // $00:$0010 and $80:$0010 must decode to the same WRAM offset
    let (r1, o1) = down(0x00, 0x0010);
    let (r2, o2) = down(0x80, 0x0010);
    assert_eq!((r1, o1), (r2, o2),
        "Bank mirroring: $00:$0010 and $80:$0010 must reach same WRAM location");
}

#[test]
fn law3_bank_mirror_rom_is_idempotent() {
    let (r1, o1) = down(0x00, 0x8000);
    let (r2, o2) = down(0x80, 0x8000);
    assert_eq!((r1, o1), (r2, o2),
        "Bank mirroring: $00:$8000 and $80:$8000 must reach same ROM offset");
}

#[test]
fn law3_bank_mirror_ppu_is_idempotent() {
    let (r1, o1) = down(0x00, 0x2100);
    let (r2, o2) = down(0x80, 0x2100);
    assert_eq!((r1, o1), (r2, o2),
        "Bank mirroring: PPU registers through $00 and $80 must agree");
}

#[test]
fn law3_bank_mirror_apu_is_idempotent() {
    let (r1, o1) = down(0x00, 0x2140);
    let (r2, o2) = down(0x80, 0x2140);
    assert_eq!((r1, o1), (r2, o2),
        "Bank mirroring: APU ports through $00 and $80 must agree");
}

#[test]
fn law3_bank_mirror_comprehensive() {
    // Test all system-area banks: $00-$3F should all agree with $80-$BF
    for bank in 0x00..=0x3Fu8 {
        for &addr in &[0x0000u16, 0x1000, 0x1FFF, 0x2100, 0x2140, 0x4200, 0x4300, 0x8000, 0xFFFF] {
            let (r1, o1) = down(bank, addr);
            let (r2, o2) = down(bank | 0x80, addr);
            assert_eq!((r1, o1), (r2, o2),
                "Bank mirroring failed: ${:02X}:{:04X} vs ${:02X}:{:04X}",
                bank, addr, bank | 0x80, addr);
        }
    }
}

// ── Law 3b: WRAM aliasing is consistent ───────────────────────────
// Three paths to WRAM: bank $7E (direct), bank $7F (upper),
// and $00-$3F:$0000-$1FFF (mirror). Where they overlap, they must
// decode to the same local offset.

#[test]
fn law3_wram_alias_direct_vs_mirror() {
    // $7E:$0010 and $00:$0010 both reach wram[0x0010]
    let (r1, o1) = down(0x7E, 0x0010);
    let (r2, o2) = down(0x00, 0x0010);
    assert_eq!(r1, Region::Wram);
    assert_eq!(r2, Region::Wram);
    assert_eq!(o1, o2,
        "WRAM direct ($7E) and mirror ($00) must agree on offset for low addresses");
}

#[test]
fn law3_wram_alias_direct_vs_mirror_boundary() {
    // $7E:$1FFF and $00:$1FFF — top of the mirror range
    let (r1, o1) = down(0x7E, 0x1FFF);
    let (r2, o2) = down(0x00, 0x1FFF);
    assert_eq!((r1, o1), (r2, o2),
        "WRAM alias at mirror boundary must agree");
}

#[test]
fn law3_wram_alias_beyond_mirror() {
    // $7E:$2000 is WRAM, but $00:$2000 is NOT WRAM (it's in the gap
    // between mirror and PPU regs). These should NOT agree.
    let (r1, _) = down(0x7E, 0x2000);
    let (r2, _) = down(0x00, 0x2000);
    assert_eq!(r1, Region::Wram, "$7E:$2000 is WRAM");
    assert_ne!(r1, r2,
        "$7E:$2000 (WRAM) and $00:$2000 (open bus / gap) must NOT be aliased");
}

#[test]
fn law3_wram_alias_data_integrity() {
    // Actually verify through the bus that aliased writes are visible
    let mut bus = test_bus();

    // Write through bank $7E
    bus.write(0x7E, 0x0042, 0xDE);
    // Read through low mirror
    assert_eq!(bus.read(0x00, 0x0042), 0xDE,
        "Write via $7E, read via mirror: Law 3 nesting through aliases");

    // Write through mirror
    bus.write(0x00, 0x0042, 0xAD);
    // Read through bank $7E
    assert_eq!(bus.read(0x7E, 0x0042), 0xAD,
        "Write via mirror, read via $7E: Law 3 nesting in reverse direction");

    // Write through mirrored bank $80
    bus.write(0x80, 0x0042, 0xBE);
    // Read through all three paths
    assert_eq!(bus.read(0x7E, 0x0042), 0xBE);
    assert_eq!(bus.read(0x00, 0x0042), 0xBE);
    assert_eq!(bus.read(0x80, 0x0042), 0xBE,
        "Three-way WRAM alias must be consistent: Law 3 across all paths");
}

// ── Law 3c: ROM aliasing is consistent ────────────────────────────
// ROM is accessible from banks $00-$3F ($8000-$FFFF), $40-$6F ($8000-$FFFF),
// and $70-$7D ($8000-$FFFF), plus their $80+ mirrors.

#[test]
fn law3_rom_alias_across_regions() {
    // Bank $00:$8000 and bank $00|$80:$8000 must read the same ROM byte
    let mut bus = test_bus();
    let v1 = bus.read(0x00, 0x8000);
    let v2 = bus.read(0x80, 0x8000);
    assert_eq!(v1, v2, "ROM alias: $00:$8000 and $80:$8000");
    assert_eq!(v1, 0x11, "ROM value at offset 0");
}

#[test]
fn law3_rom_lorom_formula_is_consistent() {
    // The LoROM formula: offset = (bank & 0x7F) * 0x8000 + (addr - 0x8000)
    // Verify it's consistent across bank ranges
    let mut bus = test_bus();

    // Bank $00, addr $8100 → offset 0x100 → rom[0x100] = 0x33
    let v = bus.read(0x00, 0x8100);
    assert_eq!(v, 0x33, "LoROM decode: bank $00, addr $8100 → offset 0x100");

    // Same through mirror: bank $80, addr $8100
    let v2 = bus.read(0x80, 0x8100);
    assert_eq!(v, v2, "LoROM formula must be consistent through bank mirror");
}

// ── Law 3d: APU port aliasing is consistent ───────────────────────
// $2140-$217F all map to 4 ports via (addr & 3). This is a quotient:
// the decode factors through mod-4.

#[test]
fn law3_apu_port_quotient() {
    // All these addresses should decode to port 0:
    // $2140, $2144, $2148, ..., $217C
    for addr in (0x2140..=0x217Cu16).step_by(4) {
        let (r, o) = down(0x00, addr);
        assert_eq!(r, Region::ApuPort);
        assert_eq!(o, 0, "APU port aliasing: ${:04X} should map to port 0", addr);
    }
    // Port 1:
    for addr in (0x2141..=0x217Du16).step_by(4) {
        let (r, o) = down(0x00, addr);
        assert_eq!(r, Region::ApuPort);
        assert_eq!(o, 1, "APU port aliasing: ${:04X} should map to port 1", addr);
    }
}

#[test]
fn law3_apu_port_quotient_data_integrity() {
    // Write to APU port 0 via $2140, read back via $2144 (mirror)
    // Both should see the SPC700's response (initially $AA)
    let mut bus = test_bus();
    let v1 = bus.read(0x00, 0x2140);
    let v2 = bus.read(0x00, 0x2144);
    assert_eq!(v1, v2,
        "APU port read through different mirrors must return same value");
}

// ═══════════════════════════════════════════════════════════════════
// LAW 5: (p + q) + r = p + (q + r)
// "Position embedding is associative"
//
// For the Bus, position embedding is address arithmetic within a
// region. This tests whether multi-step address computation
// (bank base + offset + sub-offset) is associative.
// ═══════════════════════════════════════════════════════════════════

#[test]
fn law5_wram_offset_associative() {
    // WRAM addressing: base + offset should be associative
    // (0x7E:0) + 0x100 + 0x10 = (0x7E:0) + (0x100 + 0x10)
    let mut bus = test_bus();
    bus.write(0x7E, 0x0110, 0xAA);

    // Path 1: start at 0, step by 0x100, then by 0x10
    let addr1 = 0u16.wrapping_add(0x100).wrapping_add(0x10);
    // Path 2: start at 0, step by 0x110
    let addr2 = 0u16.wrapping_add(0x110);

    assert_eq!(addr1, addr2, "Address arithmetic should be associative");
    assert_eq!(bus.read(0x7E, addr1), bus.read(0x7E, addr2),
        "WRAM read through associative address paths must agree");
}

#[test]
fn law5_lorom_bank_offset_associative() {
    // LoROM: (bank * 0x8000) + (addr - 0x8000) should be associative
    // bank=0, addr=0x8100: offset = 0*0x8000 + (0x8100 - 0x8000) = 0x100
    // Verify this equals computing the parts separately
    let bank: u32 = 0;
    let addr: u32 = 0x8100;
    let offset_direct = bank * 0x8000 + (addr - 0x8000);

    let step1 = bank * 0x8000;     // = 0
    let step2 = addr - 0x8000;      // = 0x100
    let offset_stepped = step1 + step2;

    assert_eq!(offset_direct, offset_stepped,
        "LoROM formula must be associative: direct vs stepped computation");
}

#[test]
fn law5_sram_offset_associative() {
    // SRAM: ((bank - 0x70) * 0x8000) + addr
    // Test with bank=0x70, addr=0x100 (within first 32KB SRAM bank)
    let mut bus = test_bus();
    bus.write(0x70, 0x0100, 0xCC);

    // Compute offset two ways
    let offset1 = ((0x70u32 - 0x70) * 0x8000) + 0x100;
    let offset2 = 0u32 + 0x100;
    assert_eq!(offset1, offset2, "SRAM offset calculation must be associative");

    // And verify the bus agrees
    assert_eq!(bus.read(0x70, 0x0100), 0xCC);
}

// ═══════════════════════════════════════════════════════════════════
// LAW 4: o(s) + p = p
// "Root is identity for embedding"
//
// The "root" of the Bus address space is the reset vector location:
// $00:FFFC (where PC starts). Embedding any position p through the
// root should give back p unchanged.
//
// In practice, this means: reading the reset vector, then following
// that address, is the canonical entry point. The root doesn't
// "shift" other addresses.
// ═══════════════════════════════════════════════════════════════════

#[test]
fn law4_bank_zero_is_identity_base() {
    // Bank 0 acts as the identity for bank mirroring:
    // (0 & 0x7F) | bank_offset = bank_offset (trivially)
    // The root bank doesn't shift positions
    for &addr in &[0x0000u16, 0x1000, 0x2100, 0x2140, 0x4200, 0x8000] {
        let (r1, o1) = down(0x00, addr);
        let (r2, o2) = down(0x00 & 0x7F, addr); // identity: 0 & 0x7F = 0
        assert_eq!((r1, o1), (r2, o2),
            "Root bank (0) must be identity: addr ${:04X}", addr);
    }
}

// ═══════════════════════════════════════════════════════════════════
// LAW 1: down(s, o(s)) = s
// "Subshape at root is the whole shape"
//
// If the root is the reset vector ($00:FFFC), then the sub-address-space
// visible from the reset vector should be... the full address space.
// Since the CPU at the reset vector can reach any address, this holds
// trivially. But it's worth verifying that the reset vector address
// itself decodes to a valid region (ROM).
// ═══════════════════════════════════════════════════════════════════

#[test]
fn law1_root_decodes_to_rom() {
    // The reset vector lives at $00:FFFC-FFFD, which is in ROM
    let (region, _) = down(0x00, 0xFFFC);
    assert_eq!(region, Region::Rom,
        "Reset vector address must decode to ROM region");
}

#[test]
fn law1_root_is_reachable() {
    // Verify the reset vector is readable and contains a valid address
    let mut bus = test_bus();
    let lo = bus.read(0x00, 0xFFFC) as u16;
    let hi = bus.read(0x00, 0xFFFD) as u16;
    let reset_pc = lo | (hi << 8);
    // Our test ROM has reset vector = $8000
    assert_eq!(reset_pc, 0x8000,
        "Reset vector should point to $8000 (first ROM instruction)");
}

// ═══════════════════════════════════════════════════════════════════
// SIDE-EFFECTING READS: Where the directed container structure breaks
//
// These tests document where `down` is NOT a pure function — reading
// certain registers mutates the bus state, meaning the shape changes
// after extraction. This is where the Bus fails to be a classical
// directed container and instead lives in an indexed/dependent category.
// ═══════════════════════════════════════════════════════════════════

#[test]
fn side_effect_rdnmi_mutates_shape() {
    // Reading $4210 (RDNMI) clears nmi_flag.
    // This means extract at position ($00, $4210) changes the shape.
    // Law 1 requires down(s, o(s)) = s — but if extract mutates s,
    // then s' ≠ s after extraction, violating the law.
    let mut bus = test_bus();
    bus.nmi_flag = true;

    // First read: returns flag set, clears it
    let v1 = bus.read(0x00, 0x4210);
    assert!(v1 & 0x80 != 0, "First RDNMI read should see flag set");
    assert!(!bus.nmi_flag, "RDNMI read should clear the flag");

    // Second read: flag is now clear — different value from same position
    let v2 = bus.read(0x00, 0x4210);
    assert!(v2 & 0x80 == 0, "Second RDNMI read should see flag clear");

    // This demonstrates: extract is NOT idempotent at this position.
    // The Bus is NOT a directed container at MMIO positions.
    assert_ne!(v1, v2,
        "RDNMI: consecutive reads return different values — \
         extract is not idempotent, directed container Law 1 fails here");
}

#[test]
fn side_effect_timeup_mutates_shape() {
    // $4211 (TIMEUP) — same pattern as RDNMI
    let mut bus = test_bus();
    bus.irq_flag = true;

    let v1 = bus.read(0x00, 0x4211);
    let v2 = bus.read(0x00, 0x4211);
    assert_ne!(v1, v2,
        "TIMEUP: read-clear behavior breaks extract idempotency");
}

#[test]
fn side_effect_wmdata_mutates_position() {
    // $2180 (WMDATA) — read auto-increments wram_addr.
    // This is even more severe: the read changes which WRAM byte
    // the next read will see. The position ITSELF shifts.
    let mut bus = test_bus();
    bus.wram[0] = 0xAA;
    bus.wram[1] = 0xBB;
    bus.wram_addr = 0;

    let v1 = bus.read(0x00, 0x2180); // reads wram[0], advances to 1
    let v2 = bus.read(0x00, 0x2180); // reads wram[1], advances to 2
    assert_eq!(v1, 0xAA);
    assert_eq!(v2, 0xBB);
    assert_ne!(v1, v2,
        "WMDATA: same address returns different data — \
         the position embedding itself is stateful");
}

#[test]
fn side_effect_joypad_serial_mutates_position() {
    // $4016 (Joypad serial) — each read returns the next bit.
    // Like WMDATA, the position shifts on read.
    let mut bus = test_bus();
    bus.joypad.set_button(0x8000, true); // B button
    bus.joypad.write_strobe(1);
    bus.joypad.write_strobe(0); // falling edge latches

    let _v1 = bus.read(0x00, 0x4016);
    let _v2 = bus.read(0x00, 0x4016);
    // First bit is B (bit 15, set), second is Y (bit 14, not set)
    // At least the bit index advances, so this is stateful
    // (though both might happen to return same value for different reasons)
    // The point: the read has side effects (advances bit_index)
    assert_eq!(bus.joypad.snapshot_state().len(), 6,
        "Joypad state exists and is affected by reads");
}

// ═══════════════════════════════════════════════════════════════════
// PURE MEMORY: Where the directed container structure DOES hold
//
// For pure memory (WRAM, ROM, SRAM), reads have no side effects.
// Here the Bus IS a valid directed container, and all five laws hold.
// is_pure_memory() is the predicate that separates the directed
// container from the indexed monad.
// ═══════════════════════════════════════════════════════════════════

#[test]
fn pure_memory_extract_is_idempotent() {
    // For pure memory, consecutive reads at the same address return
    // the same value — extract is idempotent, Law 1 is safe.
    let mut bus = test_bus();
    bus.write(0x7E, 0x0050, 0x42);

    let v1 = bus.read(0x7E, 0x0050);
    let v2 = bus.read(0x7E, 0x0050);
    let v3 = bus.read(0x7E, 0x0050);
    assert_eq!(v1, v2);
    assert_eq!(v2, v3);
    assert_eq!(v1, 0x42,
        "Pure memory: extract is idempotent — directed container laws hold");
}

#[test]
fn pure_memory_rom_extract_is_idempotent() {
    let mut bus = test_bus();
    let v1 = bus.read(0x00, 0x8000);
    let v2 = bus.read(0x00, 0x8000);
    assert_eq!(v1, v2,
        "ROM: extract is idempotent — reads are pure");
}

#[test]
fn pure_memory_sram_extract_is_idempotent() {
    let mut bus = test_bus();
    bus.write(0x70, 0x0000, 0x77);
    let v1 = bus.read(0x70, 0x0000);
    let v2 = bus.read(0x70, 0x0000);
    assert_eq!(v1, v2,
        "SRAM: extract is idempotent — reads are pure");
}

#[test]
fn is_pure_memory_partitions_directed_from_indexed() {
    // is_pure_memory is the exact predicate that tells us where the
    // Bus is a directed container vs where it's an indexed monad.
    let bus = test_bus();

    // Pure memory addresses: directed container laws hold
    assert!(bus.is_pure_memory(0x7E, 0x0000)); // WRAM
    assert!(bus.is_pure_memory(0x00, 0x0000)); // WRAM mirror
    assert!(bus.is_pure_memory(0x00, 0x8000)); // ROM
    assert!(bus.is_pure_memory(0x70, 0x0000)); // SRAM

    // Impure addresses: directed container laws may fail
    assert!(!bus.is_pure_memory(0x00, 0x2100)); // PPU regs
    assert!(!bus.is_pure_memory(0x00, 0x2140)); // APU ports
    assert!(!bus.is_pure_memory(0x00, 0x2180)); // WMDATA
    assert!(!bus.is_pure_memory(0x00, 0x4210)); // RDNMI
    assert!(!bus.is_pure_memory(0x00, 0x4016)); // Joypad
}

// ═══════════════════════════════════════════════════════════════════
// LAW 3 + FUNCTOR LAW: bank mirroring is a natural transformation
//
// The mirroring operation (bank & 0x7F) is an endomorphism on the
// address container. For it to be a natural transformation, it must
// commute with read: read(bank, addr) = read(bank & 0x7F, addr).
// This is stronger than just testing `down` — it verifies the
// actual data path.
// ═══════════════════════════════════════════════════════════════════

#[test]
fn bank_mirroring_naturality_wram() {
    let mut bus = test_bus();
    bus.write(0x7E, 0x0010, 0xEE);
    // Read through $00 and $80 — both must see the same WRAM byte
    assert_eq!(bus.read(0x00, 0x0010), bus.read(0x80, 0x0010),
        "Bank mirror naturality: WRAM read must commute with mirroring");
}

#[test]
fn bank_mirroring_naturality_rom() {
    let mut bus = test_bus();
    assert_eq!(bus.read(0x00, 0x8000), bus.read(0x80, 0x8000),
        "Bank mirror naturality: ROM read must commute with mirroring");
    assert_eq!(bus.read(0x01, 0x8000), bus.read(0x81, 0x8000),
        "Bank mirror naturality: ROM read (bank 1) must commute");
}

#[test]
fn bank_mirroring_naturality_sram() {
    let mut bus = test_bus();
    bus.write(0x70, 0x0000, 0xDD);
    assert_eq!(bus.read(0x70, 0x0000), bus.read(0xF0, 0x0000),
        "Bank mirror naturality: SRAM read must commute with mirroring");
}

#[test]
fn bank_mirroring_is_idempotent_morphism() {
    // mirror ∘ mirror = mirror (idempotent endomorphism)
    // (bank & 0x7F) & 0x7F = bank & 0x7F
    for bank in 0..=255u8 {
        assert_eq!(bank & 0x7F, (bank & 0x7F) & 0x7F,
            "Bank mirroring must be idempotent: bank ${:02X}", bank);
    }
}
