//! Distributive Law Test: CPU ∥ APU Composition
//!
//! The distributive law for the CPU-APU composition requires:
//!   catch_up(a + b) = catch_up(a); catch_up(b)
//!
//! That is, the APU's state after N total master cycles must be
//! independent of how those N cycles were delivered (one big chunk
//! vs many small chunks). This is the monoid homomorphism property
//! of the cycle accounting.
//!
//! Previously, the cycle_debt mechanism violated this law because
//! different chunking patterns produced different SPC instruction
//! boundary alignment. The fix replaced cycle_debt with an absolute
//! cycle_target, making run_cycles chunk-insensitive.
//!
//! Reference: Ahman, Chapman, Uustalu (2014) — distributive law
//! coherence condition 3.
//!
//! Generated by /snes-category-sweep

use rsnes::spc700::Apu;

/// Create two identical APUs in the same initial state.
fn two_fresh_apus() -> (Apu, Apu) {
    (Apu::new(), Apu::new())
}

#[test]
fn distributive_law_catch_up_100_equals_50_plus_50() {
    let (mut apu_single, mut apu_chunked) = two_fresh_apus();

    // Single chunk: 100 master cycles
    apu_single.catch_up(100 * 21); // 100 SPC cycles

    // Two chunks: 50 + 50 master cycles
    apu_chunked.catch_up(50 * 21);
    apu_chunked.catch_up(50 * 21);

    assert_eq!(apu_single.cycles, apu_chunked.cycles,
        "Distributive law: catch_up(100) must equal catch_up(50); catch_up(50) — \
         same total cycles regardless of chunking");
    assert_eq!(apu_single.sample_buffer.len(), apu_chunked.sample_buffer.len(),
        "Distributive law: same number of audio samples regardless of chunking");
    assert_eq!(apu_single.sample_buffer, apu_chunked.sample_buffer,
        "Distributive law: identical audio samples regardless of chunking");
}

#[test]
fn distributive_law_catch_up_many_small_chunks() {
    let (mut apu_single, mut apu_chunked) = two_fresh_apus();

    let total = 1000 * 21; // 1000 SPC cycles

    // Single chunk
    apu_single.catch_up(total);

    // Many small chunks (simulate per-instruction catch_up calls)
    // Various sizes to stress-test boundary alignment
    let chunks = [6, 12, 8, 6, 18, 12, 6, 8, 6, 12, 6];
    let chunk_total: u32 = chunks.iter().sum();
    let full_rounds = total / (chunk_total * 21);
    let remainder = total - full_rounds * chunk_total * 21;

    for _ in 0..full_rounds {
        for &c in &chunks {
            apu_chunked.catch_up(c * 21);
        }
    }
    if remainder > 0 {
        apu_chunked.catch_up(remainder);
    }

    assert_eq!(apu_single.cycles, apu_chunked.cycles,
        "Distributive law: many small chunks must equal one big chunk — \
         same total cycles");
    assert_eq!(apu_single.sample_buffer, apu_chunked.sample_buffer,
        "Distributive law: identical audio samples regardless of \
         how cycles are delivered");
}

#[test]
fn distributive_law_catch_up_one_cycle_at_a_time() {
    let (mut apu_single, mut apu_chunked) = two_fresh_apus();

    let total_master = 200 * 21; // 200 SPC cycles worth

    // Single chunk
    apu_single.catch_up(total_master);

    // One master cycle at a time (most extreme chunking)
    for _ in 0..total_master {
        apu_chunked.catch_up(1);
    }

    assert_eq!(apu_single.cycles, apu_chunked.cycles,
        "Distributive law extreme: one-at-a-time must equal single chunk");
    assert_eq!(apu_single.sample_buffer, apu_chunked.sample_buffer,
        "Distributive law extreme: identical audio regardless of \
         per-cycle delivery");
}

#[test]
fn distributive_law_preserves_timer_state() {
    let (mut apu_single, mut apu_chunked) = two_fresh_apus();

    let total = 500 * 21;

    apu_single.catch_up(total);

    // Asymmetric chunks
    apu_chunked.catch_up(137 * 21);
    apu_chunked.catch_up(200 * 21);
    apu_chunked.catch_up(163 * 21);

    // Timer state should be identical
    for i in 0..3 {
        let t1 = apu_single.bus.timers[i].snapshot_state();
        let t2 = apu_chunked.bus.timers[i].snapshot_state();
        assert_eq!(t1, t2,
            "Distributive law: timer {} state must be identical regardless of chunking", i);
    }
}

#[test]
fn distributive_law_preserves_dsp_state() {
    let (mut apu_single, mut apu_chunked) = two_fresh_apus();

    let total = 300 * 21;

    apu_single.catch_up(total);

    apu_chunked.catch_up(100 * 21);
    apu_chunked.catch_up(100 * 21);
    apu_chunked.catch_up(100 * 21);

    // DSP register state should be identical
    for addr in 0..128u8 {
        assert_eq!(
            apu_single.dsp_reg(addr),
            apu_chunked.dsp_reg(addr),
            "Distributive law: DSP register 0x{:02X} must be identical", addr
        );
    }
}
